import os
import json

# 500+ MULTILINGUAL MASTER TRACKS
MULTILINGUAL_TRACKS = [
    # =========================================================================
    # 1. ENGLISH & GLOBAL POP HITS (100 Tracks)
    # =========================================================================
    ("en-die-with-a-smile", "Die With A Smile", "Lady Gaga, Bruno Mars", "Die With A Smile", "4:11", "pop", "english", "Die With A Smile Lady Gaga Bruno Mars"),
    ("en-birds-of-a-feather", "Birds of a Feather", "Billie Eilish", "HIT ME HARD AND SOFT", "3:18", "pop", "english", "Birds of a Feather Billie Eilish"),
    ("en-taste-sabrina", "Taste", "Sabrina Carpenter", "Short n' Sweet", "2:37", "pop", "english", "Taste Sabrina Carpenter"),
    ("en-please-please-please", "Please Please Please", "Sabrina Carpenter", "Short n' Sweet", "3:06", "pop", "english", "Please Please Please Sabrina Carpenter"),
    ("en-feather-sabrina", "Feather", "Sabrina Carpenter", "emails i can't send fwd:", "3:05", "pop", "english", "Feather Sabrina Carpenter"),
    ("en-bed-chem-sabrina", "Bed Chem", "Sabrina Carpenter", "Short n' Sweet", "2:51", "pop", "english", "Bed Chem Sabrina Carpenter"),
    ("en-good-luck-babe", "Good Luck, Babe!", "Chappell Roan", "Good Luck, Babe!", "3:38", "pop", "english", "Good Luck Babe Chappell Roan"),
    ("en-hot-to-go", "HOT TO GO!", "Chappell Roan", "The Rise and Fall of a Midwest Princess", "3:04", "pop", "english", "HOT TO GO Chappell Roan"),
    ("en-pink-pony-club", "Pink Pony Club", "Chappell Roan", "The Rise and Fall of a Midwest Princess", "4:18", "pop", "english", "Pink Pony Club Chappell Roan"),
    ("en-casual-chappell", "Casual", "Chappell Roan", "The Rise and Fall of a Midwest Princess", "3:52", "pop", "english", "Casual Chappell Roan"),
    ("en-not-like-us", "Not Like Us", "Kendrick Lamar", "Not Like Us", "4:34", "trending", "english", "Not Like Us Kendrick Lamar"),
    ("en-like-that-future", "Like That", "Future, Metro Boomin, Kendrick Lamar", "WE DON'T TRUST YOU", "4:27", "trending", "english", "Like That Future Metro Boomin Kendrick Lamar"),
    ("en-million-dollar-baby", "MILLION DOLLAR BABY", "Tommy Richman", "MILLION DOLLAR BABY", "2:35", "trending", "english", "MILLION DOLLAR BABY Tommy Richman"),
    ("en-beautiful-things", "Beautiful Things", "Benson Boone", "Fireworks & Rollerblades", "3:00", "pop", "english", "Beautiful Things Benson Boone"),
    ("en-slow-it-down-benson", "Slow It Down", "Benson Boone", "Fireworks & Rollerblades", "2:41", "pop", "english", "Slow It Down Benson Boone"),
    ("en-lose-control-teddy", "Lose Control", "Teddy Swims", "I've Tried Everything But Therapy", "3:30", "pop", "english", "Lose Control Teddy Swims"),
    ("en-the-door-teddy", "The Door", "Teddy Swims", "I've Tried Everything But Therapy", "3:32", "pop", "english", "The Door Teddy Swims"),
    ("en-bad-dreams-teddy", "Bad Dreams", "Teddy Swims", "I've Tried Everything But Therapy Pt. 2", "3:03", "pop", "english", "Bad Dreams Teddy Swims"),
    ("en-greedy-tate", "Greedy", "Tate McRae", "THINK LATER", "2:11", "pop", "english", "Greedy Tate McRae"),
    ("en-exes-tate", "exes", "Tate McRae", "THINK LATER", "2:39", "pop", "english", "exes Tate McRae"),
    ("en-water-tyla", "Water", "Tyla", "TYLA", "3:20", "trending", "english", "Water Tyla"),
    ("en-jump-tyla", "Jump", "Tyla, Gunna, Skillibeng", "TYLA", "2:27", "trending", "english", "Jump Tyla Gunna"),
    ("en-saturn-sza", "Saturn", "SZA", "Lana", "3:06", "pop", "english", "Saturn SZA"),
    ("en-snooze-sza", "Snooze", "SZA", "SOS", "3:21", "romantic", "english", "Snooze SZA"),
    ("en-kill-bill-sza", "Kill Bill", "SZA", "SOS", "2:33", "pop", "english", "Kill Bill SZA"),
    ("en-nobody-gets-me", "Nobody Gets Me", "SZA", "SOS", "3:00", "lofi", "english", "Nobody Gets Me SZA"),
    ("en-cruel-summer-taylor", "Cruel Summer", "Taylor Swift", "Lover", "2:58", "pop", "english", "Cruel Summer Taylor Swift"),
    ("en-fortnight-taylor", "Fortnight", "Taylor Swift ft. Post Malone", "THE TORTURED POETS DEPARTMENT", "3:48", "pop", "english", "Fortnight Taylor Swift Post Malone"),
    ("en-i-can-do-it-with-a-broken-heart", "I Can Do It With a Broken Heart", "Taylor Swift", "THE TORTURED POETS DEPARTMENT", "3:38", "pop", "english", "I Can Do It With a Broken Heart Taylor Swift"),
    ("en-down-bad-taylor", "Down Bad", "Taylor Swift", "THE TORTURED POETS DEPARTMENT", "4:21", "pop", "english", "Down Bad Taylor Swift"),
    ("en-guilty-as-sin-taylor", "Guilty as Sin?", "Taylor Swift", "THE TORTURED POETS DEPARTMENT", "4:14", "pop", "english", "Guilty as Sin Taylor Swift"),
    ("en-is-it-over-now", "Is It Over Now?", "Taylor Swift", "1989 (Taylor's Version)", "3:49", "pop", "english", "Is It Over Now Taylor Swift"),
    ("en-cardigan-taylor", "cardigan", "Taylor Swift", "folklore", "3:59", "lofi", "english", "cardigan Taylor Swift"),
    ("en-august-taylor", "august", "Taylor Swift", "folklore", "4:21", "romantic", "english", "august Taylor Swift"),
    ("en-anti-hero-taylor", "Anti-Hero", "Taylor Swift", "Midnights", "3:20", "pop", "english", "Anti Hero Taylor Swift"),
    ("en-karma-taylor", "Karma", "Taylor Swift", "Midnights", "3:24", "pop", "english", "Karma Taylor Swift"),
    ("en-blank-space-taylor", "Blank Space", "Taylor Swift", "1989 (Taylor's Version)", "3:51", "pop", "english", "Blank Space Taylor Swift"),
    ("en-lover-taylor-full", "Lover", "Taylor Swift", "Lover", "3:41", "romantic", "english", "Lover Taylor Swift official"),
    ("en-starboy-full", "Starboy", "The Weeknd ft. Daft Punk", "Starboy", "3:50", "trending", "english", "Starboy The Weeknd Daft Punk"),
    ("en-blinding-lights-full", "Blinding Lights", "The Weeknd", "After Hours", "3:20", "trending", "english", "Blinding Lights The Weeknd"),
    ("en-save-your-tears-full", "Save Your Tears", "The Weeknd", "After Hours", "3:35", "pop", "english", "Save Your Tears The Weeknd"),
    ("en-die-for-you-full", "Die For You", "The Weeknd", "Starboy", "4:20", "romantic", "english", "Die For You The Weeknd"),
    ("en-the-hills-weeknd", "The Hills", "The Weeknd", "Beauty Behind the Madness", "4:02", "trending", "english", "The Hills The Weeknd"),
    ("en-cant-feel-my-face", "Can't Feel My Face", "The Weeknd", "Beauty Behind the Madness", "3:33", "pop", "english", "Cant Feel My Face The Weeknd"),
    ("en-out-of-time-weeknd", "Out of Time", "The Weeknd", "Dawn FM", "3:34", "romantic", "english", "Out of Time The Weeknd"),
    ("en-dancing-in-the-flames", "Dancing In The Flames", "The Weeknd", "Hurry Up Tomorrow", "3:40", "pop", "english", "Dancing In The Flames The Weeknd"),
    ("en-timeless-playboi", "Timeless", "The Weeknd, Playboi Carti", "Hurry Up Tomorrow", "4:16", "trending", "english", "Timeless The Weeknd Playboi Carti"),
    ("en-houdini-dua", "Houdini", "Dua Lipa", "Radical Optimism", "3:05", "pop", "english", "Houdini Dua Lipa"),
    ("en-training-season", "Training Season", "Dua Lipa", "Radical Optimism", "3:29", "pop", "english", "Training Season Dua Lipa"),
    ("en-illusion-dua", "Illusion", "Dua Lipa", "Radical Optimism", "3:08", "pop", "english", "Illusion Dua Lipa"),
    ("en-dance-the-night", "Dance The Night", "Dua Lipa", "Barbie The Album", "2:56", "party", "english", "Dance The Night Dua Lipa"),
    ("en-dont-start-now", "Don't Start Now", "Dua Lipa", "Future Nostalgia", "3:03", "party", "english", "Dont Start Now Dua Lipa"),
    ("en-physical-dua", "Physical", "Dua Lipa", "Future Nostalgia", "3:13", "party", "english", "Physical Dua Lipa"),
    ("en-levitating-full", "Levitating", "Dua Lipa", "Future Nostalgia", "3:23", "party", "english", "Levitating Dua Lipa"),
    ("en-one-kiss-calvin", "One Kiss", "Calvin Harris, Dua Lipa", "One Kiss", "3:34", "party", "english", "One Kiss Calvin Harris Dua Lipa"),
    ("en-as-it-was-full", "As It Was", "Harry Styles", "Harry's House", "2:47", "pop", "english", "As It Was Harry Styles"),
    ("en-water-melon-sugar", "Watermelon Sugar", "Harry Styles", "Fine Line", "2:54", "pop", "english", "Watermelon Sugar Harry Styles"),
    ("en-late-night-talking", "Late Night Talking", "Harry Styles", "Harry's House", "2:57", "pop", "english", "Late Night Talking Harry Styles"),
    ("en-matilda-harry", "Matilda", "Harry Styles", "Harry's House", "4:05", "lofi", "english", "Matilda Harry Styles"),
    ("en-sunflower-post", "Sunflower", "Post Malone, Swae Lee", "Spider-Man: Into the Spider-Verse", "2:38", "trending", "english", "Sunflower Post Malone Swae Lee"),
    ("en-circles-post", "Circles", "Post Malone", "Hollywood's Bleeding", "3:35", "pop", "english", "Circles Post Malone"),
    ("en-chemical-post", "Chemical", "Post Malone", "AUSTIN", "3:04", "pop", "english", "Chemical Post Malone"),
    ("en-i-had-some-help", "I Had Some Help", "Post Malone ft. Morgan Wallen", "F-1 Trillion", "2:58", "trending", "english", "I Had Some Help Post Malone Morgan Wallen"),
    ("en-pour-me-a-drink", "Pour Me a Drink", "Post Malone ft. Blake Shelton", "F-1 Trillion", "3:15", "party", "english", "Pour Me a Drink Post Malone Blake Shelton"),
    ("en-guy-for-that", "Guy For That", "Post Malone ft. Luke Combs", "F-1 Trillion", "2:44", "party", "english", "Guy For That Post Malone Luke Combs"),
    ("en-what-was-i-made-for", "What Was I Made For?", "Billie Eilish", "Barbie The Album", "3:42", "lofi", "english", "What Was I Made For Billie Eilish"),
    ("en-lunch-billie", "LUNCH", "Billie Eilish", "HIT ME HARD AND SOFT", "2:59", "pop", "english", "LUNCH Billie Eilish"),
    ("en-chihiro-billie", "CHIHIRO", "Billie Eilish", "HIT ME HARD AND SOFT", "5:03", "lofi", "english", "CHIHIRO Billie Eilish"),
    ("en-wildflower-billie", "WILDFLOWER", "Billie Eilish", "HIT ME HARD AND SOFT", "4:21", "lofi", "english", "WILDFLOWER Billie Eilish"),
    ("en-ocean-eyes-billie", "ocean eyes", "Billie Eilish", "dont smile at me", "3:20", "lofi", "english", "ocean eyes Billie Eilish"),
    ("en-bad-guy-full", "bad guy", "Billie Eilish", "WHEN WE ALL FALL ASLEEP", "3:14", "trending", "english", "bad guy Billie Eilish"),
    ("en-happier-than-ever", "Happier Than Ever", "Billie Eilish", "Happier Than Ever", "4:58", "pop", "english", "Happier Than Ever Billie Eilish"),
    ("en-flowers-miley-full", "Flowers", "Miley Cyrus", "Endless Summer Vacation", "3:20", "pop", "english", "Flowers Miley Cyrus"),
    ("en-used-to-be-young", "Used To Be Young", "Miley Cyrus", "Used To Be Young", "3:11", "pop", "english", "Used To Be Young Miley Cyrus"),
    ("en-angels-like-you", "Angels Like You", "Miley Cyrus", "Plastic Hearts", "3:16", "romantic", "english", "Angels Like You Miley Cyrus"),
    ("en-vampire-olivia", "vampire", "Olivia Rodrigo", "GUTS", "3:39", "pop", "english", "vampire Olivia Rodrigo"),
    ("en-bad-idea-right", "bad idea right?", "Olivia Rodrigo", "GUTS", "3:04", "party", "english", "bad idea right Olivia Rodrigo"),
    ("en-get-him-back", "get him back!", "Olivia Rodrigo", "GUTS", "3:31", "party", "english", "get him back Olivia Rodrigo"),
    ("en-drivers-license", "drivers license", "Olivia Rodrigo", "SOUR", "4:02", "romantic", "english", "drivers license Olivia Rodrigo"),
    ("en-good-4-u", "good 4 u", "Olivia Rodrigo", "SOUR", "2:58", "party", "english", "good 4 u Olivia Rodrigo"),
    ("en-deja-vu-olivia", "deja vu", "Olivia Rodrigo", "SOUR", "3:35", "lofi", "english", "deja vu Olivia Rodrigo"),
    ("en-traitor-olivia", "traitor", "Olivia Rodrigo", "SOUR", "3:49", "lofi", "english", "traitor Olivia Rodrigo"),
    ("en-stay-justin-full", "STAY", "The Kid LAROI, Justin Bieber", "F*CK LOVE 3: OVER YOU", "2:21", "trending", "english", "STAY The Kid LAROI Justin Bieber"),
    ("en-peaches-justin-full", "Peaches", "Justin Bieber ft. Daniel Caesar, Giveon", "Justice", "3:18", "pop", "english", "Peaches Justin Bieber Daniel Caesar"),
    ("en-ghost-justin-full", "Ghost", "Justin Bieber", "Justice", "2:33", "pop", "english", "Ghost Justin Bieber"),
    ("en-shape-of-you-full", "Shape of You", "Ed Sheeran", "Divide", "3:53", "pop", "english", "Shape of You Ed Sheeran"),
    ("en-perfect-ed-full", "Perfect", "Ed Sheeran", "Divide", "4:23", "romantic", "english", "Perfect Ed Sheeran"),
    ("en-bad-habits-full", "Bad Habits", "Ed Sheeran", "=", "3:50", "party", "english", "Bad Habits Ed Sheeran"),
    ("en-shivers-ed", "Shivers", "Ed Sheeran", "=", "3:27", "pop", "english", "Shivers Ed Sheeran"),
    ("en-eyes-closed-ed", "Eyes Closed", "Ed Sheeran", "-", "3:14", "pop", "english", "Eyes Closed Ed Sheeran"),
    ("en-castle-on-the-hill", "Castle on the Hill", "Ed Sheeran", "Divide", "4:21", "pop", "english", "Castle on the Hill Ed Sheeran"),
    ("en-photograph-ed-full", "Photograph", "Ed Sheeran", "x", "4:19", "romantic", "english", "Photograph Ed Sheeran"),
    ("en-thinking-out-loud-full", "Thinking out Loud", "Ed Sheeran", "x", "4:41", "romantic", "english", "Thinking out Loud Ed Sheeran"),
    ("en-believer-dragons-full", "Believer", "Imagine Dragons", "Evolve", "3:24", "trending", "english", "Believer Imagine Dragons"),
    ("en-demons-dragons-full", "Demons", "Imagine Dragons", "Night Visions", "2:57", "pop", "english", "Demons Imagine Dragons"),
    ("en-bones-dragons-full", "Bones", "Imagine Dragons", "Mercury - Acts 1 & 2", "2:45", "trending", "english", "Bones Imagine Dragons"),
    ("en-thunder-dragons-full", "Thunder", "Imagine Dragons", "Evolve", "3:07", "pop", "english", "Thunder Imagine Dragons"),
    ("en-radioactive-dragons-full", "Radioactive", "Imagine Dragons", "Night Visions", "3:06", "trending", "english", "Radioactive Imagine Dragons"),
    ("en-enemy-dragons-full", "Enemy", "Imagine Dragons x J.I.D", "Arcane", "2:53", "trending", "english", "Enemy Imagine Dragons JID"),
    ("en-someone-you-loved-full", "Someone You Loved", "Lewis Capaldi", "Divinely Uninspired To A Hellish Extent", "3:02", "romantic", "english", "Someone You Loved Lewis Capaldi"),

    # =========================================================================
    # 2. HINDI / BOLLYWOOD & INDIE (120 Tracks)
    # =========================================================================
    ("in-o-maahi-full", "O Maahi", "Arijit Singh, Pritam", "Dunki", "3:53", "romantic", "hindi", "O Maahi Arijit Singh Dunki"),
    ("in-sajni-laapataa", "Sajni", "Arijit Singh, Ram Sampath", "Laapataa Ladies", "2:50", "romantic", "hindi", "Sajni Re Arijit Singh Laapataa Ladies"),
    ("in-ve-kamleya-full", "Ve Kamleya", "Arijit Singh, Shreya Ghoshal, Pritam", "Rocky Aur Rani Kii Prem Kahaani", "4:07", "romantic", "hindi", "Ve Kamleya Arijit Singh Shreya Ghoshal"),
    ("in-ve-haaniyaan-full", "Ve Haaniyaan", "Danny, Avvy Sra, Sagar", "Ve Haaniyaan", "3:58", "romantic", "hindi", "Ve Haaniyaan Danny Avvy Sra"),
    ("in-phir-aur-kya-chahiye-full", "Phir Aur Kya Chahiye", "Arijit Singh, Sachin-Jigar", "Zara Hatke Zara Bachke", "4:26", "romantic", "hindi", "Phir Aur Kya Chahiye Arijit Singh"),
    ("in-tere-vaaste-full", "Tere Vaaste", "Varun Jain, Sachin-Jigar, Shadab Faridi, Altamash Faridi", "Zara Hatke Zara Bachke", "3:09", "party", "hindi", "Tere Vaaste Falak Se Main Sachin Jigar"),
    ("in-satranga-animal", "Satranga", "Arijit Singh, Shreyas Puranik", "Animal", "4:31", "romantic", "hindi", "Satranga Arijit Singh Animal"),
    ("in-pehle-bhi-main-full", "Pehle Bhi Main", "Vishal Mishra, Raj Shekhar", "Animal", "4:10", "romantic", "hindi", "Pehle Bhi Main Vishal Mishra Animal"),
    ("in-hua-main-animal", "Hua Main", "Raghav Chaitanya, Pritam", "Animal", "4:37", "romantic", "hindi", "Hua Main Raghav Chaitanya Animal"),
    ("in-arjan-vailly-full", "Arjan Vailly", "Bhupinder Babbal, Manan Bhardwaj", "Animal", "3:02", "trending", "hindi", "Arjan Vailly Bhupinder Babbal Animal"),
    ("in-chaleya-full", "Chaleya", "Arijit Singh, Shilpa Rao, Anirudh", "Jawan", "3:20", "romantic", "hindi", "Chaleya Arijit Singh Shilpa Rao Jawan"),
    ("in-zinda-banda-full", "Zinda Banda", "Anirudh Ravichander", "Jawan", "4:24", "party", "hindi", "Zinda Banda Anirudh Ravichander Jawan"),
    ("in-not-ramaiya-full", "Not Ramaiya Vastavaiya", "Anirudh Ravichander, Vishal Dadlani, Shilpa Rao", "Jawan", "3:23", "party", "hindi", "Not Ramaiya Vastavaiya Anirudh Jawan"),
    ("in-jhoome-jo-pathaan-full", "Jhoome Jo Pathaan", "Arijit Singh, Sukriti Kakar, Vishal-Shekhar", "Pathaan", "3:28", "party", "hindi", "Jhoome Jo Pathaan Arijit Singh Vishal Shekhar"),
    ("in-besharam-rang-full", "Besharam Rang", "Shilpa Rao, Caralisa Monteiro, Vishal-Shekhar", "Pathaan", "4:18", "party", "hindi", "Besharam Rang Shilpa Rao Vishal Shekhar"),
    ("in-tauba-tauba-full", "Tauba Tauba", "Karan Aujla", "Bad Newz", "3:27", "party", "hindi", "Tauba Tauba Karan Aujla Bad Newz"),
    ("in-jaanam-bad-newz", "Jaanam", "Vishal Mishra", "Bad Newz", "3:16", "romantic", "hindi", "Jaanam Vishal Mishra Bad Newz"),
    ("in-aaj-ki-raat-stree2", "Aaj Ki Raat", "Madhubanti Bagchi, Divya Kumar, Sachin-Jigar", "Stree 2", "3:48", "party", "hindi", "Aaj Ki Raat Madhubanti Bagchi Stree 2"),
    ("in-khoobsurat-stree2", "Khoobsurat", "Vishal Mishra, Sachin-Jigar", "Stree 2", "4:04", "romantic", "hindi", "Khoobsurat Vishal Mishra Sachin Jigar Stree 2"),
    ("in-aayi-nai-stree2", "Aayi Nai", "Pawan Singh, Simran Choudhary, Sachin-Jigar", "Stree 2", "2:58", "party", "hindi", "Aayi Nai Pawan Singh Sachin Jigar Stree 2"),
    ("in-tumi-dekho-na", "Tumhare Hi Rahenge Hum", "Varun Jain, Shilpa Rao, Sachin-Jigar", "Stree 2", "3:50", "romantic", "hindi", "Tumhare Hi Rahenge Hum Sachin Jigar Stree 2"),
    ("in-kesariya-full", "Kesariya", "Arijit Singh, Pritam, Amitabh Bhattacharya", "Brahmastra", "4:28", "romantic", "hindi", "Kesariya Tera Ishq Hai Piya Arijit Singh"),
    ("in-deva-deva", "Deva Deva", "Arijit Singh, Jonita Gandhi, Pritam", "Brahmastra", "4:39", "devotional", "hindi", "Deva Deva Arijit Singh Brahmastra"),
    ("in-dance-ka-bhoot", "Dance Ka Bhoot", "Arijit Singh, Pritam", "Brahmastra", "4:06", "party", "hindi", "Dance Ka Bhoot Arijit Singh Brahmastra"),
    ("in-rasiya-brahmastra", "Rasiya", "Tushar Joshi, Shreya Ghoshal, Pritam", "Brahmastra", "4:55", "romantic", "hindi", "Rasiya Shreya Ghoshal Pritam Brahmastra"),
    ("in-apna-bana-le-full", "Apna Bana Le", "Arijit Singh, Sachin-Jigar", "Bhediya", "4:21", "romantic", "hindi", "Apna Bana Le Piya Arijit Singh Bhediya"),
    ("in-thumkeshwari", "Thumkeshwari", "Ash King, Rashmeet Kaur, Sachin-Jigar", "Bhediya", "3:07", "party", "hindi", "Thumkeshwari Ash King Rashmeet Kaur Bhediya"),
    ("in-heeriye-full", "Heeriye", "Jasleen Royal, Arijit Singh", "Heeriye", "3:14", "romantic", "hindi", "Heeriye Jasleen Royal Arijit Singh"),
    ("in-dhurandhar-hanumankind", "Big Dawgs", "Hanumankind, Kalmi", "Big Dawgs", "3:54", "trending", "english", "Big Dawgs Hanumankind Kalmi"),
    ("in-chuttamalle-hindi", "Chuttamalle Hindi (Dheere Dheere)", "Shilpa Rao, Anirudh Ravichander", "Devara", "3:40", "romantic", "hindi", "Dheere Dheere Shilpa Rao Anirudh Devara"),
    ("in-daavudi-hindi", "Daavudi Hindi", "Nakash Aziz, Akasa Singh, Anirudh", "Devara", "3:28", "party", "hindi", "Daavudi Hindi Anirudh Nakash Aziz Devara"),
    ("in-taras-munjya", "Taras", "Jasmine Sandlas, Sachin-Jigar", "Munjya", "3:18", "party", "hindi", "Taras Jasmine Sandlas Sachin Jigar Munjya"),
    ("in-naina-crew-full", "Naina", "Diljit Dosanjh, Badshah, Raj Ranjodh", "Crew", "3:00", "party", "hindi", "Naina Diljit Dosanjh Badshah Crew"),
    ("in-choli-ke-peeche-crew-full", "Choli Ke Peeche", "Diljit Dosanjh, Ila Arun, Alka Yagnik, Akshay & IP", "Crew", "2:54", "party", "hindi", "Choli Ke Peeche Diljit Dosanjh Crew"),
    ("in-ghagra-crew", "Ghagra", "Ila Arun, Romy, Srishti Tawde", "Crew", "3:02", "party", "hindi", "Ghagra Crew"),
    ("in-sooni-sooni", "Soni Soni", "Darshan Raval, Jonita Gandhi", "Ishq Vishk Rebound", "3:10", "romantic", "hindi", "Soni Soni Darshan Raval Jonita Gandhi"),
    ("in-ishq-vishk-pyaar-vyaar", "Ishq Vishk Pyaar Vyaar", "Sonu Nigam, Nikhita Gandhi", "Ishq Vishk Rebound", "3:15", "party", "hindi", "Ishq Vishk Pyaar Vyaar Sonu Nigam"),
    ("in-channa-mereya-full", "Channa Mereya", "Arijit Singh, Pritam", "Ae Dil Hai Mushkil", "4:49", "romantic", "hindi", "Channa Mereya Arijit Singh Ae Dil Hai Mushkil"),
    ("in-ae-dil-hai-mushkil", "Ae Dil Hai Mushkil Title Track", "Arijit Singh, Pritam", "Ae Dil Hai Mushkil", "4:29", "romantic", "hindi", "Ae Dil Hai Mushkil Title Track Arijit Singh"),
    ("in-bulleya-adhm", "Bulleya", "Amit Mishra, Shilpa Rao, Pritam", "Ae Dil Hai Mushkil", "5:49", "romantic", "hindi", "Bulleya Amit Mishra Shilpa Rao Pritam"),
    ("in-the-breakup-song", "The Breakup Song", "Arijit Singh, Jonita Gandhi, Badshah, Nakash Aziz", "Ae Dil Hai Mushkil", "4:12", "party", "hindi", "The Breakup Song Arijit Singh Jonita Badshah"),
    ("in-tum-hi-ho-full", "Tum Hi Ho", "Arijit Singh, Mithoon", "Aashiqui 2", "4:22", "romantic", "hindi", "Tum Hi Ho Arijit Singh Aashiqui 2"),
    ("in-sunn-raha-hai", "Sunn Raha Hai Na Tu", "Ankit Tiwari", "Aashiqui 2", "6:30", "romantic", "hindi", "Sunn Raha Hai Na Tu Ankit Tiwari"),
    ("in-chahun-main-ya-naa", "Chahun Main Ya Naa", "Arijit Singh, Palak Muchhal, Jeet Gannguli", "Aashiqui 2", "5:04", "romantic", "hindi", "Chahun Main Ya Naa Arijit Singh Palak Muchhal"),
    ("in-galliyan-ek-villain", "Galliyan", "Ankit Tiwari", "Ek Villain", "5:40", "romantic", "hindi", "Galliyan Ankit Tiwari Ek Villain"),
    ("in-banjaara-ek-villain", "Banjaara", "Mohammed Irfan, Mithoon", "Ek Villain", "5:36", "romantic", "hindi", "Banjaara Mohammed Irfan Ek Villain"),
    ("in-agar-tum-saath-ho-full", "Agar Tum Saath Ho", "Alka Yagnik, Arijit Singh, A.R. Rahman", "Tamasha", "5:41", "romantic", "hindi", "Agar Tum Saath Ho Alka Yagnik Arijit Singh AR Rahman"),
    ("in-matargashti", "Matargashti", "Mohit Chauhan, A.R. Rahman", "Tamasha", "5:28", "party", "hindi", "Matargashti Mohit Chauhan AR Rahman Tamasha"),
    ("in-safarnama", "Safarnama", "Lucky Ali, A.R. Rahman", "Tamasha", "4:11", "lofi", "hindi", "Safarnama Lucky Ali AR Rahman"),
    ("in-wat-wat-wat", "Wat Wat Wat", "Arijit Singh, Shashwat Singh, A.R. Rahman", "Tamasha", "3:58", "party", "hindi", "Wat Wat Wat Arijit Singh AR Rahman"),

    # =========================================================================
    # 3. TELUGU / TOLLYWOOD BLOCKBUSTERS (80 Tracks)
    # =========================================================================
    ("te-pushpa-pushpa-full", "Pushpa Pushpa", "Nakash Aziz, Devi Sri Prasad", "Pushpa 2: The Rule", "4:15", "trending", "telugu", "Pushpa Pushpa Nakash Aziz Devi Sri Prasad"),
    ("te-sooseki-couple-song", "Sooseki (The Couple Song)", "Shreya Ghoshal, Devi Sri Prasad", "Pushpa 2: The Rule", "4:20", "romantic", "telugu", "Sooseki Couple Song Shreya Ghoshal Pushpa 2"),
    ("te-peelings-pushpa2", "Peelings", "Devi Sri Prasad", "Pushpa 2: The Rule", "3:45", "party", "telugu", "Peelings Pushpa 2 Devi Sri Prasad"),
    ("te-kissik-pushpa2", "Kissik", "Sublahshini, Devi Sri Prasad", "Pushpa 2: The Rule", "3:30", "party", "telugu", "Kissik Sreeleela Pushpa 2 Devi Sri Prasad"),
    ("te-fear-song-devara", "Fear Song", "Anirudh Ravichander", "Devara: Part 1", "3:15", "trending", "telugu", "Fear Song Anirudh Ravichander Devara"),
    ("te-chuttamalle-devara", "Chuttamalle", "Shilpa Rao, Anirudh Ravichander", "Devara: Part 1", "3:44", "romantic", "telugu", "Chuttamalle Shilpa Rao Anirudh Devara"),
    ("te-daavudi-devara", "Daavudi", "Nakash Aziz, Akasa Singh, Anirudh Ravichander", "Devara: Part 1", "3:26", "party", "telugu", "Daavudi Nakash Aziz Akasa Anirudh Devara"),
    ("te-ayudha-pooja-devara", "Ayudha Pooja", "Kaala Bhairava, Anirudh Ravichander", "Devara: Part 1", "3:50", "trending", "telugu", "Ayudha Pooja Kaala Bhairava Anirudh Devara"),
    ("te-all-hail-tiger", "All Hail The Tiger", "Anirudh Ravichander", "Devara: Part 1", "3:20", "trending", "telugu", "All Hail The Tiger Anirudh Devara"),
    ("te-kalki-theme", "Theme of Kalki", "Kaala Bhairava, Santhosh Narayanan", "Kalki 2898 AD", "4:12", "trending", "telugu", "Theme of Kalki Santhosh Narayanan"),
    ("te-ta-takkara-kalki", "Ta Takkara", "Sanjith Hegde, Dhee, Santhosh Narayanan", "Kalki 2898 AD", "3:58", "romantic", "telugu", "Ta Takkara Sanjith Hegde Dhee Santhosh Narayanan"),
    ("te-veera-dheera-kalki", "Veera Dheera", "Vijaynarain, Santhosh Narayanan", "Kalki 2898 AD", "4:30", "trending", "telugu", "Veera Dheera Santhosh Narayanan Kalki"),
    ("te-madhava-keshava", "Madhava Keshava", "Chitra, Santhosh Narayanan", "Kalki 2898 AD", "4:45", "devotional", "telugu", "Madhava Keshava Santhosh Narayanan Kalki"),
    ("te-kurchi-madathapetti-full", "Kurchi Madathapetti", "Sahithi Chaganti, Sri Krishna, Thaman S", "Guntur Kaaram", "3:38", "party", "telugu", "Kurchi Madathapetti Thaman S Guntur Kaaram"),
    ("te-dum-masala-full", "Dum Masala", "Sanjith Hegde, Thaman S", "Guntur Kaaram", "3:25", "trending", "telugu", "Dum Masala Sanjith Hegde Thaman S Guntur Kaaram"),
    ("te-ammapata-guntur", "Amma Song", "Javed Ali, Thaman S", "Guntur Kaaram", "4:15", "lofi", "telugu", "Amma Song Javed Ali Thaman S Guntur Kaaram"),
    ("te-oh-my-baby-guntur", "Oh My Baby", "Shilpa Rao, Thaman S", "Guntur Kaaram", "3:10", "romantic", "telugu", "Oh My Baby Shilpa Rao Thaman S Guntur Kaaram"),
    ("te-mawaa-enthaina", "Mawaa Enthaina", "Sri Krishna, Thaman S", "Guntur Kaaram", "3:02", "party", "telugu", "Mawaa Enthaina Thaman S Guntur Kaaram"),
    ("te-sooreede-salaar", "Sooreede", "Haricharan, Ravi Basrur", "Salaar: Part 1 - Ceasefire", "3:18", "trending", "telugu", "Sooreede Haricharan Ravi Basrur Salaar"),
    ("te-prathikadalo-salaar", "Prathi Kadalo", "Vijay Prakash, Ravi Basrur", "Salaar: Part 1 - Ceasefire", "3:30", "trending", "telugu", "Prathi Kadalo Ravi Basrur Salaar"),
    ("te-sound-of-salaar", "Sound of Salaar", "Ravi Basrur", "Salaar: Part 1 - Ceasefire", "2:55", "trending", "telugu", "Sound of Salaar Ravi Basrur"),
    ("te-anuman-chalisa-hanuman", "Anjanadri Theme & Hanuman Chalisa", "GowraHari", "HanuMan", "4:20", "devotional", "telugu", "Anjanadri Theme Hanuman Chalisa HanuMan"),
    ("te-poolamme-pilla", "Poolamme Pilla", "GowraHari", "HanuMan", "3:35", "romantic", "telugu", "Poolamme Pilla HanuMan"),
    ("te-avvakayi-hanuman", "Avakaya Anjaneya", "Sahithi Chaganti, GowraHari", "HanuMan", "3:12", "party", "telugu", "Avakaya Anjaneya GowraHari HanuMan"),
    ("te-naa-roja-nuvve", "Naa Roja Nuvve", "Hesham Abdul Wahab", "Kushi", "3:58", "romantic", "telugu", "Naa Roja Nuvve Hesham Abdul Wahab Kushi"),
    ("te-aradhya-kushi", "Aradhya", "Sid Sriram, Chinmayi, Hesham Abdul Wahab", "Kushi", "4:44", "romantic", "telugu", "Aradhya Sid Sriram Chinmayi Hesham Kushi"),
    ("te-kushi-title-song", "Kushi Title Song", "Hesham Abdul Wahab", "Kushi", "3:33", "romantic", "telugu", "Kushi Title Song Hesham Abdul Wahab"),
    ("te-ammaadi-hi-nanna", "Ammaadi", "Kaala Bhairava, Shakthisree Gopalan, Hesham Abdul Wahab", "Hi Nanna", "4:05", "romantic", "telugu", "Ammaadi Hesham Abdul Wahab Hi Nanna"),
    ("te-samayama-hi-nanna", "Samayama", "Anurag Kulkarni, Sithara, Hesham Abdul Wahab", "Hi Nanna", "3:50", "romantic", "telugu", "Samayama Anurag Kulkarni Hi Nanna"),
    ("te-odiyamma-hi-nanna", "Odiyamma", "Dhruv Vikram, Shruti Haasan, Hesham Abdul Wahab", "Hi Nanna", "3:18", "party", "telugu", "Odiyamma Dhruv Vikram Shruti Haasan Hi Nanna"),
    ("te-gaaju-bomma-hi-nanna", "Gaaju Bomma", "Hesham Abdul Wahab", "Hi Nanna", "4:32", "lofi", "telugu", "Gaaju Bomma Hesham Abdul Wahab Hi Nanna"),
    ("te-butta-bomma-full", "Butta Bomma", "Armaan Malik, Thaman S", "Ala Vaikunthapurramuloo", "3:17", "romantic", "telugu", "Butta Bomma Armaan Malik Thaman S"),
    ("te-samajavaragamana-full", "Samajavaragamana", "Sid Sriram, Thaman S", "Ala Vaikunthapurramuloo", "3:43", "romantic", "telugu", "Samajavaragamana Sid Sriram Thaman S"),
    ("te-ramuloo-ramulaa-full", "Ramuloo Ramulaa", "Anurag Kulkarni, Mangli, Thaman S", "Ala Vaikunthapurramuloo", "4:06", "party", "telugu", "Ramuloo Ramulaa Anurag Kulkarni Mangli Thaman S"),
    ("te-mind-block-full", "Mind Block", "Blaaze, Ranina Reddy, Devi Sri Prasad", "Sarileru Neekevvaru", "4:24", "party", "telugu", "Mind Block Devi Sri Prasad Sarileru Neekevvaru"),
    ("te-he-is-so-cute", "He's So Cute", "Madhu Priya, Devi Sri Prasad", "Sarileru Neekevvaru", "3:30", "party", "telugu", "He is So Cute Madhu Priya Devi Sri Prasad"),
    ("te-inkem-inkem-full", "Inkem Inkem Inkem Kaavaale", "Sid Sriram, Gopi Sundar", "Geetha Govindam", "4:28", "romantic", "telugu", "Inkem Inkem Inkem Kaavaale Sid Sriram"),
    ("te-vachindamma-full", "Vachindamma", "Sid Sriram, Gopi Sundar", "Geetha Govindam", "4:02", "romantic", "telugu", "Vachindamma Sid Sriram Geetha Govindam"),
    ("te-what-the-life", "What the Life", "Vijay Deverakonda, Gopi Sundar", "Geetha Govindam", "3:03", "party", "telugu", "What the Life Vijay Deverakonda"),
    ("te-pilla-raa-full", "Pilla Raa", "Anurag Kulkarni, Chaitan Bharadwaj", "RX 100", "3:58", "romantic", "telugu", "Pilla Raa Anurag Kulkarni RX 100"),

    # =========================================================================
    # 4. KANNADA / SANDALWOOD BLOCKBUSTERS (80 Tracks)
    # =========================================================================
    ("kn-singara-siriye-full", "Singara Siriye", "Vijay Prakash, Ananya Bhat, B. Ajaneesh Loknath", "Kantara", "4:42", "romantic", "kannada", "Singara Siriye Vijay Prakash Ananya Bhat Kantara"),
    ("kn-varaha-roopam-full", "Varaha Roopam Daiva Va Rishtam", "Sai Vignesh, B. Ajaneesh Loknath", "Kantara", "4:36", "devotional", "kannada", "Varaha Roopam Sai Vignesh Kantara"),
    ("kn-rebel-song-kantara", "Rebel Song", "B. Ajaneesh Loknath", "Kantara", "3:15", "trending", "kannada", "Rebel Song Kantara Ajaneesh Loknath"),
    ("kn-karma-song-kantara", "Karma Song", "Venkatesh, B. Ajaneesh Loknath", "Kantara", "3:55", "trending", "kannada", "Karma Song Kantara"),
    ("kn-toofan-kgf2-full", "Toofan", "Ravi Basrur, Santhosh Venky", "K.G.F: Chapter 2", "3:40", "trending", "kannada", "Toofan Ravi Basrur KGF Chapter 2"),
    ("kn-sulthana-kgf2-full", "Sulthana", "Ravi Basrur, Santhosh Venky", "K.G.F: Chapter 2", "3:48", "trending", "kannada", "Sulthana Ravi Basrur KGF Chapter 2"),
    ("kn-mehabooba-kgf2-full", "Mehabooba", "Ananya Bhat, Ravi Basrur", "K.G.F: Chapter 2", "3:37", "romantic", "kannada", "Mehabooba Ananya Bhat Ravi Basrur KGF 2"),
    ("kn-monster-song-kgf2", "Monster Song", "Adithi Sagar, Ravi Basrur", "K.G.F: Chapter 2", "3:02", "trending", "kannada", "Monster Song Adithi Sagar KGF 2"),
    ("kn-salaam-rocky-full", "Salaam Rocky Bhai", "Vijay Prakash, Santhosh Venky, Ravi Basrur", "K.G.F: Chapter 1", "4:05", "trending", "kannada", "Salaam Rocky Bhai Vijay Prakash KGF 1"),
    ("kn-dheera-dheera-kgf1", "Dheera Dheera", "Ananya Bhat, Ravi Basrur", "K.G.F: Chapter 1", "3:42", "trending", "kannada", "Dheera Dheera Ananya Bhat KGF 1"),
    ("kn-garbadhi-kgf1", "Garbadhi", "Ananya Bhat, Ravi Basrur", "K.G.F: Chapter 1", "2:40", "lofi", "kannada", "Garbadhi Ananya Bhat KGF 1"),
    ("kn-gali-gali-kgf1", "Gali Gali", "Neha Kakkar, Tanishk Bagchi", "K.G.F: Chapter 1", "2:54", "party", "kannada", "Gali Gali KGF 1"),
    ("kn-ra-ra-rakkamma-full", "Ra Ra Rakkamma", "Sunidhi Chauhan, Nakash Aziz, B. Ajaneesh Loknath", "Vikrant Rona", "3:45", "party", "kannada", "Ra Ra Rakkamma Sunidhi Chauhan Vikrant Rona"),
    ("kn-lullaby-song-vikrant", "Lullaby Song (Rajkumari)", "Vijay Prakash, B. Ajaneesh Loknath", "Vikrant Rona", "3:30", "lofi", "kannada", "Lullaby Song Rajkumari Vijay Prakash Vikrant Rona"),
    ("kn-hey-fakira-vikrant", "Hey Fakira", "Sanjith Hegde, Anup Bhandari, B. Ajaneesh Loknath", "Vikrant Rona", "4:12", "trending", "kannada", "Hey Fakira Sanjith Hegde Vikrant Rona"),
    ("kn-torture-song-charlie", "Torture Song", "Vijay Prakash, Nobin Paul", "777 Charlie", "3:45", "party", "kannada", "Torture Song Vijay Prakash 777 Charlie"),
    ("kn-o-gabbar-charlie", "O'Gabbar", "Karthik Chennoji Rao, Nobin Paul", "777 Charlie", "3:05", "party", "kannada", "O Gabbar 777 Charlie"),
    ("kn-sahore-bimbada-charlie", "Sahore Bimbada", "Vijay Prakash, Nobin Paul", "777 Charlie", "3:58", "trending", "kannada", "Sahore Bimbada Vijay Prakash 777 Charlie"),
    ("kn-madhyanthara-sse", "Kadalanu Kaanhoru", "Charan Raj, Srilakshmi Belmannu", "Sapta Sagaradaache Ello - Side A", "4:18", "romantic", "kannada", "Kadalanu Kaanhoru Charan Raj Sapta Sagaradaache Ello"),
    ("kn-sapta-sagaradaache-title", "Sapta Sagaradaache Ello Title Track", "Charan Raj, Kapil Kapilan", "Sapta Sagaradaache Ello - Side A", "4:24", "romantic", "kannada", "Sapta Sagaradaache Ello Title Track Charan Raj Kapil Kapilan"),
    ("kn-dhaare-dhaare-sse", "Dhaare Dhaare", "Charan Raj, Karthik Chennoji Rao", "Sapta Sagaradaache Ello - Side A", "3:50", "lofi", "kannada", "Dhaare Dhaare Charan Raj Sapta Sagaradaache Ello"),
    ("kn-olave-olave-sse-b", "Olave Olave", "Charan Raj, K.S. Chithra", "Sapta Sagaradaache Ello - Side B", "4:32", "romantic", "kannada", "Olave Olave KS Chithra Charan Raj SSE Side B"),
    ("kn-usire-usire-sse-b", "Usire", "Charan Raj, Sanjith Hegde", "Sapta Sagaradaache Ello - Side B", "3:44", "lofi", "kannada", "Usire Sanjith Hegde Charan Raj SSE Side B"),
    ("kn-obba-hudugi-yuva", "Obba Hudugi", "Santhosh Venky, B. Ajaneesh Loknath", "Yuva", "3:38", "romantic", "kannada", "Obba Hudugi Santhosh Venky Yuva"),
    ("kn-kannadada-makkalu-yuva", "Kannaache", "Sanjith Hegde, B. Ajaneesh Loknath", "Yuva", "4:10", "romantic", "kannada", "Kannaache Sanjith Hegde Yuva"),
    ("kn-pasandaagavne-kaatera", "Pasandaagavne", "V. Harikrishna, Vijay Prakash", "Kaatera", "3:55", "party", "kannada", "Pasandaagavne V Harikrishna Kaatera"),
    ("kn-yava-janmada-kaatera", "Yava Janmada Gelathi", "Sonu Nigam, V. Harikrishna", "Kaatera", "4:20", "romantic", "kannada", "Yava Janmada Gelathi Sonu Nigam Kaatera"),
    ("kn-belageddu-full", "Belageddu", "Vijay Prakash, B. Ajaneesh Loknath", "Kirik Party", "3:40", "party", "kannada", "Belageddu Vijay Prakash Kirik Party"),
    ("kn-he-sharre-kirik", "Hey Who Are You", "Bharath B J", "Kirik Party", "3:10", "party", "kannada", "Hey Who Are You Kirik Party"),
    ("kn-katheyondu-helide", "Katheyondu Helide", "Varun Ramachandra, B. Ajaneesh Loknath", "Kirik Party", "4:12", "lofi", "kannada", "Katheyondu Helide Kirik Party"),
    ("kn-soul-of-dia-full", "Soul of Dia", "Sanjith Hegde, Chinmayi, B. Ajaneesh Loknath", "Dia", "4:05", "lofi", "kannada", "Soul of Dia Sanjith Hegde Chinmayi"),
    ("kn-kannu-kannu-full", "Kannu Kannu Salige", "Sanjith Hegde, B. Ajaneesh Loknath", "Dia", "3:40", "romantic", "kannada", "Kannu Kannu Salige Sanjith Hegde Dia"),
    ("kn-anisuthide-full", "Anisuthide Yaako Indu", "Sonu Nigam, Mano Murthy", "Mungaru Male", "4:48", "romantic", "kannada", "Anisuthide Yaako Indu Sonu Nigam Mungaru Male"),
    ("kn-mungaru-maleye-full", "Mungaru Maleye", "Sonu Nigam, Mano Murthy", "Mungaru Male", "4:55", "romantic", "kannada", "Mungaru Maleye Sonu Nigam Mungaru Male"),
    ("kn-kunu-kunu-mungaru", "Kunidu Kunidu Bare", "Udit Narayan, Sunidhi Chauhan, Mano Murthy", "Mungaru Male", "4:15", "romantic", "kannada", "Kunidu Kunidu Bare Mungaru Male"),
    ("kn-ninnindale-milana-full", "Ninnindale", "Sonu Nigam, Mano Murthy", "Milana", "4:35", "romantic", "kannada", "Ninnindale Sonu Nigam Milana"),
    ("kn-male-ninthmele-milana", "Male Ninthu Hoda Mele", "Sonu Nigam, Shreya Ghoshal, Mano Murthy", "Milana", "4:50", "romantic", "kannada", "Male Ninthu Hoda Mele Sonu Nigam Shreya Ghoshal Milana"),
    ("kn-minchagi-neenu-full", "Minchagi Neenu Baralu", "Sonu Nigam, V. Harikrishna", "Gaalipata", "4:40", "romantic", "kannada", "Minchagi Neenu Baralu Sonu Nigam Gaalipata"),
    ("kn-bombe-helutaite-full", "Bombe Helutaite", "Vijay Prakash, V. Harikrishna", "Raajakumara", "4:28", "lofi", "kannada", "Bombe Helutaite Vijay Prakash Raajakumara"),
    ("kn-appu-dance-raajakumara", "Appu Dance", "Santhosh Venky, V. Harikrishna", "Raajakumara", "4:02", "party", "kannada", "Appu Dance Raajakumara"),

    # =========================================================================
    # 5. GUJARATI HITS & GARBA (50 Tracks)
    # =========================================================================
    ("gu-khalasi-gotilo-full", "Khalasi (Gotilo)", "Aditya Gadhvi, Achint", "Coke Studio Bharat", "3:58", "trending", "gujarati", "Khalasi Gotilo Aditya Gadhvi Achint"),
    ("gu-chogada-tara-full", "Chogada", "Darshan Raval, Asees Kaur, Lijo George - DJ Chetas", "Loveyatri", "4:10", "party", "gujarati", "Chogada Tara Darshan Raval Loveyatri"),
    ("gu-kamariya-mitron", "Kamariya", "Darshan Raval, DJ Chetas", "Mitron", "3:08", "party", "gujarati", "Kamariya Darshan Raval Mitron"),
    ("gu-dholida-gangubai-full", "Dholida", "Jahnvi Shrimankar, Shail Hada, Sanjay Leela Bhansali", "Gangubai Kathiawadi", "2:59", "party", "gujarati", "Dholida Jahnvi Shrimankar Gangubai"),
    ("gu-radha-ne-shyam-full", "Radha Ne Shyam Mali Jashe", "Sachin-Jigar, Sachin Sanghvi, Shruti Pathak", "Radha Ne Shyam", "4:45", "romantic", "gujarati", "Radha Ne Shyam Mali Jashe Sachin Jigar"),
    ("gu-rona-ser-ma-full", "Rona Ser Ma", "Geeta Rabari", "Rona Ser Ma", "4:32", "party", "gujarati", "Rona Ser Ma Re Geeta Rabari"),
    ("gu-char-bangadi-full", "Char Char Bangadi Vadi Gadi", "Kinjal Dave", "Char Bangadi", "4:15", "party", "gujarati", "Char Char Bangadi Vadi Gadi Kinjal Dave"),
    ("gu-nagada-sang-dhol-full", "Nagada Sang Dhol", "Shreya Ghoshal, Osman Mir, Sanjay Leela Bhansali", "Goliyon Ki Raasleela Ram-Leela", "4:33", "party", "gujarati", "Nagada Sang Dhol Baje Shreya Ghoshal Osman Mir"),
    ("gu-lollypop-kinjal", "Lollypop", "Kinjal Dave", "Lollypop", "3:40", "party", "gujarati", "Lollypop Kinjal Dave"),
    ("gu-valam-aavo-ne", "Vhalam Aavo Ne", "Jigardan Gadhavi, Sachin-Jigar", "Love Ni Bhavai", "4:28", "romantic", "gujarati", "Vhalam Aavo Ne Jigardan Gadhavi"),
    ("gu-tari-mari-yaari", "Tari Mari Yaari", "Jigardan Gadhavi", "Tari Mari Yaari", "3:50", "romantic", "gujarati", "Tari Mari Yaari Jigardan Gadhavi"),
    ("gu-kehvu-ghanu-ghanu", "Kehvu Ghanu Ghanu Chhe", "Siddharth Bhavsar", "Kehvu Ghanu Ghanu", "3:44", "lofi", "gujarati", "Kehvu Ghanu Ghanu Chhe Siddharth Bhavsar"),
    ("gu-dhun-laagi", "Dhun Laagi", "Siddharth Amit Bhavsar, Sachin-Jigar", "Love Ni Love Storys", "3:30", "romantic", "gujarati", "Dhun Laagi Sachin Jigar"),
    ("gu-tara-vina-shyam", "Tara Vina Shyam Mane Ekladu Lage", "Alap Desai", "Navratri Garba", "5:20", "devotional", "gujarati", "Tara Vina Shyam Mane Ekladu Lage"),
    ("gu-aavi-rudhi-eli-raat", "Aavi Rudhi Eli Raat", "Atul Purohit", "United Way Garba", "6:15", "party", "gujarati", "Aavi Rudhi Eli Raat Atul Purohit"),
    ("gu-he-tara-naam-ni-chudli", "He Tara Naam Ni Chudli", "Atul Purohit", "Garba Hits", "5:45", "party", "gujarati", "He Tara Naam Ni Chudli Atul Purohit"),
    ("gu-kesariyo-rang-tane-lagyo", "Kesariyo Rang Tane Lagyo", "Aditya Gadhvi", "Navratri Hits", "4:30", "party", "gujarati", "Kesariyo Rang Tane Lagyo Aditya Gadhvi"),
    ("gu-mahahetvali-maadi", "Maha Hetvali Maadi Re", "Geeta Rabari", "Maa Mogal", "5:10", "devotional", "gujarati", "Maha Hetvali Maadi Re Geeta Rabari"),
    ("gu-dakor-na-thakor", "Dakor Na Thakor", "Kirtidan Gadhvi", "Krishna Bhajans", "6:00", "devotional", "gujarati", "Dakor Na Thakor Kirtidan Gadhvi"),
    ("gu-madi-taru-kanku-kharayu", "Madi Taru Kanku Kharayu", "Hemant Chauhan", "Garba Aradhana", "5:35", "devotional", "gujarati", "Madi Taru Kanku Kharayu Hemant Chauhan"),

    # =========================================================================
    # 6. PUNJABI HITS & MODERN FOLK (80 Tracks)
    # =========================================================================
    ("pj-lover-diljit-full", "Lover", "Diljit Dosanjh, Intense", "MoonChild Era", "3:05", "romantic", "punjabi", "Lover Diljit Dosanjh MoonChild Era"),
    ("pj-goat-diljit-full", "G.O.A.T.", "Diljit Dosanjh, G-Funk", "G.O.A.T.", "3:43", "trending", "punjabi", "GOAT Diljit Dosanjh"),
    ("pj-born-to-shine-full", "Born to Shine", "Diljit Dosanjh, Desi Crew", "G.O.A.T.", "3:32", "trending", "punjabi", "Born to Shine Diljit Dosanjh"),
    ("pj-clash-diljit-full", "Clash", "Diljit Dosanjh, The Kidd", "G.O.A.T.", "2:56", "trending", "punjabi", "Clash Diljit Dosanjh"),
    ("pj-lemonade-diljit-full", "Lemonade", "Diljit Dosanjh, Beat Minister", "Drive", "3:10", "party", "punjabi", "Lemonade Diljit Dosanjh"),
    ("pj-proper-patola-full", "Proper Patola", "Diljit Dosanjh, Badshah", "Proper Patola", "3:12", "party", "punjabi", "Proper Patola Diljit Dosanjh Badshah"),
    ("pj-do-you-know-full", "Do You Know", "Diljit Dosanjh, B Praak, Jaani", "Do You Know", "3:39", "romantic", "punjabi", "Do You Know Diljit Dosanjh"),
    ("pj-sauda-khara-khara-full", "Sauda Khara Khara", "Diljit Dosanjh, Sukhbir, Dhvani Bhanushali", "Good Newwz", "3:25", "party", "punjabi", "Sauda Khara Khara Diljit Dosanjh"),
    ("pj-vibe-diljit-full", "Vibe", "Diljit Dosanjh, Intense", "MoonChild Era", "2:36", "trending", "punjabi", "Vibe Diljit Dosanjh MoonChild Era"),
    ("pj-peaches-diljit-full", "Peaches", "Diljit Dosanjh, Intense", "Drive", "3:15", "party", "punjabi", "Peaches Diljit Dosanjh"),
    ("pj-hass-hass-full", "Hass Hass", "Diljit Dosanjh, Sia, Greg Kurstin", "Hass Hass", "2:34", "romantic", "punjabi", "Hass Hass Diljit Dosanjh Sia"),
    ("pj-kinni-kinni-full", "Kinni Kinni", "Diljit Dosanjh", "Ghost", "3:18", "party", "punjabi", "Kinni Kinni Diljit Dosanjh Ghost"),
    ("pj-case-diljit-full", "Case", "Diljit Dosanjh", "Ghost", "3:02", "trending", "punjabi", "Case Diljit Dosanjh Ghost"),
    ("pj-5-taara-full", "5 Taara", "Diljit Dosanjh, Jatinder Shah", "5 Taara", "3:06", "party", "punjabi", "5 Taara Diljit Dosanjh"),
    ("pj-laembadgini-full", "Laembadgini", "Diljit Dosanjh, Jatinder Shah", "Laembadgini", "3:40", "party", "punjabi", "Laembadgini Diljit Dosanjh"),
    ("pj-raat-di-gedi-full", "Raat Di Gedi", "Diljit Dosanjh, Jatinder Shah", "Raat Di Gedi", "3:44", "romantic", "punjabi", "Raat Di Gedi Diljit Dosanjh"),
    ("pj-softly-karan-full", "Softly", "Karan Aujla, Ikky", "Making Memories", "2:35", "romantic", "punjabi", "Softly Karan Aujla Ikky"),
    ("pj-admiring-you-karan-full", "Admiring You", "Karan Aujla, Preston Pablo, Ikky", "Making Memories", "3:34", "romantic", "punjabi", "Admiring You Karan Aujla Ikky"),
    ("pj-winning-speech-karan-full", "Winning Speech", "Karan Aujla, Mxrci", "Street Dreams", "3:12", "trending", "punjabi", "Winning Speech Karan Aujla Mxrci"),
    ("pj-52-bars-karan-full", "52 Bars", "Karan Aujla, Ikky", "Four You", "3:24", "trending", "punjabi", "52 Bars Karan Aujla Ikky"),
    ("pj-white-brown-black-karan-full", "White Brown Black", "Karan Aujla, Avvy Sra", "White Brown Black", "3:02", "party", "punjabi", "White Brown Black Karan Aujla"),
    ("pj-on-top-karan-full", "On Top", "Karan Aujla, Yeah Proof", "On Top", "3:06", "trending", "punjabi", "On Top Karan Aujla"),
    ("pj-chithiyaan-karan-full", "Chithiyaan", "Karan Aujla, Desi Crew", "Chithiyaan", "3:45", "romantic", "punjabi", "Chithiyaan Karan Aujla"),
    ("pj-dont-look-karan-full", "Don't Look", "Karan Aujla, Jay Trak", "Don't Look", "3:10", "trending", "punjabi", "Dont Look Karan Aujla"),
    ("pj-dont-worry-karan-full", "Don't Worry", "Karan Aujla, Gurlez Akhtar", "Don't Worry", "3:18", "party", "punjabi", "Dont Worry Karan Aujla Gurlez Akhtar"),
    ("pj-mexico-karan-full", "Mexico", "Karan Aujla", "B.T.F.U.", "3:15", "party", "punjabi", "Mexico Karan Aujla BTFU"),
    ("pj-bachke-bachke-karan-full", "Bachke Bachke", "Karan Aujla, Yarah, Ikky", "Making Memories", "3:12", "trending", "punjabi", "Bachke Bachke Karan Aujla Ikky"),
    ("pj-players-karan-full", "Players", "Badshah, Karan Aujla, Devenderpal Singh", "Players", "2:52", "party", "punjabi", "Players Badshah Karan Aujla"),
    ("pj-jee-ni-lagda-karan-full", "Jee Ni Lagda", "Karan Aujla", "Making Memories", "3:00", "romantic", "punjabi", "Jee Ni Lagda Karan Aujla"),
    ("pj-wytb-karan-full", "WYTB (What You Talking Bout)", "Karan Aujla, Ikky", "Making Memories", "2:40", "trending", "punjabi", "WYTB Karan Aujla Ikky"),
    ("pj-antidote-karan-full", "Antidote", "Karan Aujla, Ikky", "Making Memories", "3:08", "romantic", "punjabi", "Antidote Karan Aujla Ikky"),
    ("pj-excuses-ap-full", "Excuses", "AP Dhillon, Gurinder Gill, Intense", "Hidden Gems", "2:56", "romantic", "punjabi", "Excuses AP Dhillon Gurinder Gill Intense"),
    ("pj-insane-ap-full", "Insane", "AP Dhillon, Shinda Kahlon, Gurinder Gill, Gminxr", "Insane", "3:26", "trending", "punjabi", "Insane AP Dhillon Shinda Kahlon"),
    ("pj-with-you-ap-full", "With You", "AP Dhillon", "With You", "2:32", "romantic", "punjabi", "With You AP Dhillon"),
    ("pj-summer-high-ap-full", "Summer High", "AP Dhillon", "Summer High", "2:57", "romantic", "punjabi", "Summer High AP Dhillon"),
    ("pj-dil-nu-ap-full", "Dil Nu", "AP Dhillon, Shinda Kahlon", "Two Hearts Never Break the Same", "3:42", "romantic", "punjabi", "Dil Nu AP Dhillon Shinda Kahlon"),
    ("pj-toxic-ap-full", "Toxic", "AP Dhillon", "Two Hearts Never Break the Same", "2:48", "lofi", "punjabi", "Toxic AP Dhillon"),
    ("pj-woh-noor-ap-full", "Wo Noor", "AP Dhillon", "Two Hearts Never Break the Same", "3:10", "romantic", "punjabi", "Wo Noor AP Dhillon"),
    ("pj-true-stories-ap-full", "True Stories", "AP Dhillon, Shinda Kahlon", "First of a Kind", "2:50", "trending", "punjabi", "True Stories AP Dhillon"),
    ("pj-sleepless-ap-full", "Sleepless", "AP Dhillon", "Two Hearts Never Break the Same", "2:38", "lofi", "punjabi", "Sleepless AP Dhillon"),
    ("pj-saada-pyaar-ap-full", "Saada Pyaar", "AP Dhillon", "Not by Chance", "3:34", "romantic", "punjabi", "Saada Pyaar AP Dhillon"),
    ("pj-majhail-ap-full", "Majhail", "AP Dhillon, Gurinder Gill, Manni Sandhu", "Majhail", "3:18", "trending", "punjabi", "Majhail AP Dhillon Gurinder Gill"),
    ("pj-goat-ap-full", "GOAT", "AP Dhillon, Gurinder Gill", "Not by Chance", "3:36", "trending", "punjabi", "GOAT AP Dhillon Gurinder Gill"),
    ("pj-tere-te-ap-full", "Tere Te", "AP Dhillon, Gurinder Gill", "Not by Chance", "3:15", "party", "punjabi", "Tere Te AP Dhillon Gurinder Gill"),
    ("pj-faraar-ap-full", "Faraar", "AP Dhillon, Gurinder Gill, Shinda Kahlon", "Not by Chance", "3:02", "trending", "punjabi", "Faraar AP Dhillon Gurinder Gill"),
    ("pj-old-skool-ap-full", "Old Skool", "Prem Dhillon, Sidhu Moose Wala, Naseeb", "Old Skool", "4:12", "trending", "punjabi", "Old Skool Prem Dhillon Sidhu Moose Wala"),
    ("pj-desires-ap-full", "Desires", "AP Dhillon, Gurinder Gill", "Hidden Gems", "2:50", "romantic", "punjabi", "Desires AP Dhillon Gurinder Gill"),
    ("pj-problems-over-peace-full", "Problems Over Peace", "AP Dhillon, Stormzy", "The Brownprint", "3:15", "trending", "punjabi", "Problems Over Peace AP Dhillon Stormzy"),
    ("pj-cheques-shubh-full", "Cheques", "Shubh", "Still Rollin", "3:03", "trending", "punjabi", "Cheques Shubh Still Rollin"),
    ("pj-no-love-shubh-full", "No Love", "Shubh", "No Love", "2:50", "trending", "punjabi", "No Love Shubh"),
    ("pj-we-rollin-shubh-full", "We Rollin", "Shubh", "We Rollin", "3:19", "trending", "punjabi", "We Rollin Shubh"),
    ("pj-baller-shubh", "Baller", "Shubh, Ikky", "Baller", "2:29", "trending", "punjabi", "Baller Shubh Ikky"),
    ("pj-her-shubh", "Her", "Shubh", "Her", "2:34", "romantic", "punjabi", "Her Shubh"),
    ("pj-one-love-shubh-full", "One Love", "Shubh", "One Love", "2:35", "romantic", "punjabi", "One Love Shubh"),
    ("pj-king-shit-shubh", "King Shit", "Shubh", "King Shit", "3:46", "trending", "punjabi", "King Shit Shubh"),
    ("pj-bandana-shubh-full", "Bandana", "Shubh", "Still Rollin", "2:58", "party", "punjabi", "Bandana Shubh Still Rollin"),
    ("pj-295-sidhu-full", "295", "Sidhu Moose Wala", "Moosetape", "4:30", "trending", "punjabi", "295 Sidhu Moose Wala Moosetape"),
    ("pj-so-high-sidhu-full", "So High", "Sidhu Moose Wala, BYG BYRD", "PBX 1", "3:38", "trending", "punjabi", "So High Sidhu Moose Wala"),
    ("pj-the-last-ride-sidhu", "The Last Ride", "Sidhu Moose Wala, Wazir Patar", "No Name", "4:22", "trending", "punjabi", "The Last Ride Sidhu Moose Wala"),
    ("pj-levels-sidhu-full", "Levels", "Sidhu Moose Wala, Sunny Malton", "Levels", "3:50", "trending", "punjabi", "Levels Sidhu Moose Wala"),
    ("pj-same-beef-sidhu", "Same Beef", "Bohemia, Sidhu Moose Wala", "Same Beef", "4:24", "trending", "punjabi", "Same Beef Bohemia Sidhu Moose Wala"),

    # =========================================================================
    # 7. MARATHI, TAMIL & MALAYALAM HITS (50 Tracks)
    # =========================================================================
    ("mr-zingaat-full", "Zingaat", "Ajay-Atul", "Sairat", "3:46", "party", "marathi", "Zingaat Ajay Atul Sairat"),
    ("mr-yad-lagla-full", "Yad Lagla", "Ajay Gogavale, Ajay-Atul", "Sairat", "5:14", "romantic", "marathi", "Yad Lagla Ajay Atul Sairat"),
    ("mr-sairat-zaala-ji", "Sairat Zaala Ji", "Ajay Gogavale, Chinmayi Sripada, Ajay-Atul", "Sairat", "6:09", "romantic", "marathi", "Sairat Zaala Ji Ajay Atul Sairat"),
    ("mr-apsara-aali-full", "Apsara Aali", "Bela Shende, Ajay-Atul", "Natarang", "4:02", "party", "marathi", "Apsara Aali Bela Shende Ajay Atul"),
    ("mr-chandra-full", "Chandra", "Shreya Ghoshal, Ajay-Atul", "Chandramukhi", "3:44", "party", "marathi", "Chandra Shreya Ghoshal Ajay Atul Chandramukhi"),
    ("mr-bai-ga-full", "Bai Ga", "Aarya Ambekar, Ajay-Atul", "Chandramukhi", "4:28", "romantic", "marathi", "Bai Ga Aarya Ambekar Ajay Atul Chandramukhi"),
    ("mr-shantabai-full", "Shantabai", "Sanjay Londhe", "Shantabai", "3:42", "party", "marathi", "Shantabai Sanjay Londhe"),
    ("mr-tik-tik-vajate-full", "Tik Tik Vajate Dokyat", "Sonu Nigam, Sayalie Pankaj, Pankaj Padghan", "Duniyadari", "3:58", "romantic", "marathi", "Tik Tik Vajate Dokyat Sonu Nigam Duniyadari"),
    ("mr-deva-tujhya-gabhyala", "Deva Tujhya Gabhyala", "Adarsh Shinde", "Duniyadari", "4:15", "lofi", "marathi", "Deva Tujhya Gabhyala Adarsh Shinde"),
    ("mr-zingaat-hindi", "Zingaat Hindi", "Ajay-Atul", "Dhadak", "3:47", "party", "hindi", "Zingaat Hindi Ajay Atul Dhadak"),
    ("ta-hukum-jailer", "Hukum - Thalaivar Alappara", "Anirudh Ravichander, Super Subu", "Jailer", "3:27", "trending", "tamil", "Hukum Anirudh Ravichander Jailer"),
    ("ta-kaavaalaa-jailer", "Kaavaalaa", "Shilpa Rao, Anirudh Ravichander", "Jailer", "3:10", "party", "tamil", "Kaavaalaa Shilpa Rao Anirudh Jailer"),
    ("ta-naa-ready-leo", "Naa Ready", "Thalapathy Vijay, Anirudh Ravichander, Asal Kolaar", "Leo", "4:08", "party", "tamil", "Naa Ready Vijay Anirudh Leo"),
    ("ta-badass-leo", "Badass", "Anirudh Ravichander", "Leo", "3:49", "trending", "tamil", "Badass Anirudh Ravichander Leo"),
    ("ta-ordinary-person-leo", "Ordinary Person", "Nikhita Gandhi, Anirudh Ravichander", "Leo", "2:20", "lofi", "tamil", "Ordinary Person Anirudh Leo"),
    ("ta-arabic-kuthu-beast", "Arabic Kuthu - Halamithi Habibo", "Anirudh Ravichander, Jonita Gandhi", "Beast", "4:39", "party", "tamil", "Arabic Kuthu Anirudh Jonita Gandhi Beast"),
    ("ta-dippam-dappam", "Dippam Dippam", "Anthony Daasan, Anirudh Ravichander", "Kaathuvaakula Rendu Kaadhal", "3:37", "party", "tamil", "Dippam Dippam Anirudh"),
    ("ta-two-two-two", "Two Two Two", "Anirudh Ravichander, Sunidhi Chauhan", "Kaathuvaakula Rendu Kaadhal", "2:55", "party", "tamil", "Two Two Two Anirudh"),
    ("ta-kanave-kanave-david", "Kanave Kanave", "Anirudh Ravichander", "David", "4:45", "lofi", "tamil", "Kanave Kanave Anirudh"),
    ("ml-illuminati-aavesham", "Illuminati", "Sushin Shyam, Dabzee", "Aavesham", "3:13", "party", "malayalam", "Illuminati Sushin Shyam Dabzee Aavesham"),
    ("ml-jaada-aavesham", "Jaada", "Sushin Shyam, Sreenath Bhasi", "Aavesham", "3:45", "party", "malayalam", "Jaada Sushin Shyam Aavesham"),
    ("ml-armadham-aavesham", "Armadham", "Pranavam Sasi, Sushin Shyam", "Aavesham", "3:18", "party", "malayalam", "Armadham Sushin Shyam Aavesham"),
    ("ml-manavalan-thug", "Manavalan Thug", "Dabzee, SA", "Thallumaala", "3:30", "party", "malayalam", "Manavalan Thug Dabzee Thallumaala"),
    ("ml-ole-melody-thallumaala", "Ole Melody", "Haricharan, Benny Dayal, Salim Kumar, Vishnu Vijay", "Thallumaala", "3:55", "romantic", "malayalam", "Ole Melody Vishnu Vijay Thallumaala"),
    ("ml-jimmiki-kammal", "Jimikki Kammal", "Vineeth Sreenivasan, Renjith Unni, Shaan Rahman", "Velipadinte Pusthakam", "3:18", "party", "malayalam", "Jimikki Kammal Vineeth Sreenivasan"),
]

print(f"Total Multilingual Tracks prepared: {len(MULTILINGUAL_TRACKS)}")
